language: ruby
rvm:
 - 2.3.1
# Enable headless testing with chrome
dist: trusty
addons:
  chrome: stable
# Headless test setup
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # Install ChromeDriver (64bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/bin
  - sudo chmod +x /usr/local/bin/chromedriver
# Copy sample credentials to expected path
before_script:
  - cp spec/support/cloudinary-sample-credentials.yml spec/dummy/config/cloudinary.yml
  - bundle exec rake db:setup
# Run RSpec
script:
  bundle exec rake
