language: ruby
rvm:
 - 2.3.1
# Enable headless testing with chrome
dist: trusty
addons:
  chrome: stable
# Install ChromeDriver (64bits).
before_install:
  - wget -N http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/bin
  - sudo chmod +x /usr/local/bin/chromedriver
# Copy sample credentials to expected path
before_script:
  - cp spec/support/cloudinary-sample-credentials.yml spec/dummy/config/cloudinary.yml
  - bundle exec rake db:setup
# Run RSpec
script:
  bundle exec rake
